export interface CountryType {
  code: string
  label: string
  phone: string
  suggested?: boolean
}
export const countries: readonly CountryType[] = [
  { code: "AD", label: "Andorra", phone: "+376" },
  {
    code: "AE",
    label: "United Arab Emirates",
    phone: "+971",
  },
  { code: "AF", label: "Afghanistan", phone: "+93" },
  {
    code: "AG",
    label: "Antigua and Barbuda",
    phone: "+1-268",
  },
  { code: "AI", label: "Anguilla", phone: "+1-264" },
  { code: "AL", label: "Albania", phone: "+355" },
  { code: "AM", label: "Armenia", phone: "+374" },
  { code: "AO", label: "Angola", phone: "+244" },
  { code: "AQ", label: "Antarctica", phone: "+672" },
  { code: "AR", label: "Argentina", phone: "+54" },
  { code: "AS", label: "American Samoa", phone: "+1-684" },
  { code: "AT", label: "Austria", phone: "+43" },
  {
    code: "AU",
    label: "Australia",
    phone: "+61",
    suggested: true,
  },
  { code: "AW", label: "Aruba", phone: "+297" },
  { code: "AX", label: "Alland Islands", phone: "+358" },
  { code: "AZ", label: "Azerbaijan", phone: "+994" },
  {
    code: "BA",
    label: "Bosnia and Herzegovina",
    phone: "+387",
  },
  { code: "BB", label: "Barbados", phone: "+1-246" },
  { code: "BD", label: "Bangladesh", phone: "+880" },
  { code: "BE", label: "Belgium", phone: "+32" },
  { code: "BF", label: "Burkina Faso", phone: "+226" },
  { code: "BG", label: "Bulgaria", phone: "+359" },
  { code: "BH", label: "Bahrain", phone: "+973" },
  { code: "BI", label: "Burundi", phone: "+257" },
  { code: "BJ", label: "Benin", phone: "+229" },
  { code: "BL", label: "Saint Barthelemy", phone: "+590" },
  { code: "BM", label: "Bermuda", phone: "+1-441" },
  { code: "BN", label: "Brunei Darussalam", phone: "+673" },
  { code: "BO", label: "Bolivia", phone: "+591" },
  { code: "BR", label: "Brazil", phone: "+55" },
  { code: "BS", label: "Bahamas", phone: "+1-242" },
  { code: "BT", label: "Bhutan", phone: "+975" },
  { code: "BV", label: "Bouvet Island", phone: "+47" },
  { code: "BW", label: "Botswana", phone: "+267" },
  { code: "BY", label: "Belarus", phone: "+375" },
  { code: "BZ", label: "Belize", phone: "+501" },
  {
    code: "CA",
    label: "Canada",
    phone: "+1",
    suggested: true,
  },
  {
    code: "CC",
    label: "Cocos (Keeling) Islands",
    phone: "+61",
  },
  {
    code: "CD",
    label: "Congo, Democratic Republic of the",
    phone: "+243",
  },
  {
    code: "CF",
    label: "Central African Republic",
    phone: "+236",
  },
  {
    code: "CG",
    label: "Congo, Republic of the",
    phone: "+242",
  },
  { code: "CH", label: "Switzerland", phone: "+41" },
  { code: "CI", label: "Cote d'Ivoire", phone: "+225" },
  { code: "CK", label: "Cook Islands", phone: "+682" },
  { code: "CL", label: "Chile", phone: "+56" },
  { code: "CM", label: "Cameroon", phone: "+237" },
  { code: "CN", label: "China", phone: "+86" },
  { code: "CO", label: "Colombia", phone: "+57" },
  { code: "CR", label: "Costa Rica", phone: "+506" },
  { code: "CU", label: "Cuba", phone: "+53" },
  { code: "CV", label: "Cape Verde", phone: "+238" },
  { code: "CW", label: "Curacao", phone: "+599" },
  { code: "CX", label: "Christmas Island", phone: "+61" },
  { code: "CY", label: "Cyprus", phone: "+357" },
  { code: "CZ", label: "Czech Republic", phone: "+420" },
  {
    code: "DE",
    label: "Germany",
    phone: "+49",
    suggested: true,
  },
  { code: "DJ", label: "Djibouti", phone: "+253" },
  { code: "DK", label: "Denmark", phone: "+45" },
  { code: "DM", label: "Dominica", phone: "+1-767" },
  {
    code: "DO",
    label: "Dominican Republic",
    phone: "+1-809",
  },
  { code: "DZ", label: "Algeria", phone: "+213" },
  { code: "EC", label: "Ecuador", phone: "+593" },
  { code: "EE", label: "Estonia", phone: "+372" },
  { code: "EG", label: "Egypt", phone: "+20" },
  { code: "EH", label: "Western Sahara", phone: "+212" },
  { code: "ER", label: "Eritrea", phone: "+291" },
  { code: "ES", label: "Spain", phone: "+34" },
  { code: "ET", label: "Ethiopia", phone: "+251" },
  { code: "FI", label: "Finland", phone: "+358" },
  { code: "FJ", label: "Fiji", phone: "+679" },
  {
    code: "FK",
    label: "Falkland Islands (Malvinas)",
    phone: "+500",
  },
  {
    code: "FM",
    label: "Micronesia, Federated States of",
    phone: "+691",
  },
  { code: "FO", label: "Faroe Islands", phone: "+298" },
  {
    code: "FR",
    label: "France",
    phone: "+33",
    suggested: true,
  },
  { code: "GA", label: "Gabon", phone: "+241" },
  { code: "GB", label: "United Kingdom", phone: "+44" },
  { code: "GD", label: "Grenada", phone: "+1-473" },
  { code: "GE", label: "Georgia", phone: "+995" },
  { code: "GF", label: "French Guiana", phone: "+594" },
  { code: "GG", label: "Guernsey", phone: "+44" },
  { code: "GH", label: "Ghana", phone: "+233" },
  { code: "GI", label: "Gibraltar", phone: "+350" },
  { code: "GL", label: "Greenland", phone: "+299" },
  { code: "GM", label: "Gambia", phone: "+220" },
  { code: "GN", label: "Guinea", phone: "+224" },
  { code: "GP", label: "Guadeloupe", phone: "+590" },
  { code: "GQ", label: "Equatorial Guinea", phone: "+240" },
  { code: "GR", label: "Greece", phone: "+30" },
  {
    code: "GS",
    label: "South Georgia and the South Sandwich Islands",
    phone: "+500",
  },
  { code: "GT", label: "Guatemala", phone: "+502" },
  { code: "GU", label: "Guam", phone: "+1-671" },
  { code: "GW", label: "Guinea-Bissau", phone: "+245" },
  { code: "GY", label: "Guyana", phone: "+592" },
  { code: "HK", label: "Hong Kong", phone: "+852" },
  {
    code: "HM",
    label: "Heard Island and McDonald Islands",
    phone: "+672",
  },
  { code: "HN", label: "Honduras", phone: "+504" },
  { code: "HR", label: "Croatia", phone: "+385" },
  { code: "HT", label: "Haiti", phone: "+509" },
  { code: "HU", label: "Hungary", phone: "+36" },
  { code: "ID", label: "Indonesia", phone: "+62" },
  { code: "IE", label: "Ireland", phone: "+353" },
  { code: "IL", label: "Israel", phone: "+972" },
  { code: "IM", label: "Isle of Man", phone: "+44" },
  { code: "IN", label: "India", phone: "+91" },
  {
    code: "IO",
    label: "British Indian Ocean Territory",
    phone: "+246",
  },
  { code: "IQ", label: "Iraq", phone: "+964" },
  {
    code: "IR",
    label: "Iran, Islamic Republic of",
    phone: "+98",
  },
  { code: "IS", label: "Iceland", phone: "+354" },
  { code: "IT", label: "Italy", phone: "+39" },
  { code: "JE", label: "Jersey", phone: "+44" },
  { code: "JM", label: "Jamaica", phone: "+1-876" },
  { code: "JO", label: "Jordan", phone: "+962" },
  {
    code: "JP",
    label: "Japan",
    phone: "+81",
    suggested: true,
  },
  { code: "KE", label: "Kenya", phone: "+254" },
  { code: "KG", label: "Kyrgyzstan", phone: "+996" },
  { code: "KH", label: "Cambodia", phone: "+855" },
  { code: "KI", label: "Kiribati", phone: "+686" },
  { code: "KM", label: "Comoros", phone: "+269" },
  {
    code: "KN",
    label: "Saint Kitts and Nevis",
    phone: "+1-869",
  },
  {
    code: "KP",
    label: "Korea, Democratic People's Republic of",
    phone: "+850",
  },
  { code: "KR", label: "Korea, Republic of", phone: "+82" },
  { code: "KW", label: "Kuwait", phone: "+965" },
  { code: "KY", label: "Cayman Islands", phone: "+1-345" },
  { code: "KZ", label: "Kazakhstan", phone: "+7" },
  {
    code: "LA",
    label: "Lao People's Democratic Republic",
    phone: "+856",
  },
  { code: "LB", label: "Lebanon", phone: "+961" },
  { code: "LC", label: "Saint Lucia", phone: "+1-758" },
  { code: "LI", label: "Liechtenstein", phone: "+423" },
  { code: "LK", label: "Sri Lanka", phone: "+94" },
  { code: "LR", label: "Liberia", phone: "+231" },
  { code: "LS", label: "Lesotho", phone: "+266" },
  { code: "LT", label: "Lithuania", phone: "+370" },
  { code: "LU", label: "Luxembourg", phone: "+352" },
  { code: "LV", label: "Latvia", phone: "+371" },
  { code: "LY", label: "Libya", phone: "+218" },
  { code: "MA", label: "Morocco", phone: "+212" },
  { code: "MC", label: "Monaco", phone: "+377" },
  {
    code: "MD",
    label: "Moldova, Republic of",
    phone: "+373",
  },
  { code: "ME", label: "Montenegro", phone: "+382" },
  {
    code: "MF",
    label: "Saint Martin (French part)",
    phone: "+590",
  },
  { code: "MG", label: "Madagascar", phone: "+261" },
  { code: "MH", label: "Marshall Islands", phone: "+692" },
  {
    code: "MK",
    label: "Macedonia, the Former Yugoslav Republic of",
    phone: "+389",
  },
  { code: "ML", label: "Mali", phone: "+223" },
  { code: "MM", label: "Myanmar", phone: "+95" },
  { code: "MN", label: "Mongolia", phone: "+976" },
  { code: "MO", label: "Macao", phone: "+853" },
  {
    code: "MP",
    label: "Northern Mariana Islands",
    phone: "+1-670",
  },
  { code: "MQ", label: "Martinique", phone: "+596" },
  { code: "MR", label: "Mauritania", phone: "+222" },
  { code: "MS", label: "Montserrat", phone: "+1-664" },
  { code: "MT", label: "Malta", phone: "+356" },
  { code: "MU", label: "Mauritius", phone: "+230" },
  { code: "MV", label: "Maldives", phone: "+960" },
  { code: "MW", label: "Malawi", phone: "+265" },
  { code: "MX", label: "Mexico", phone: "+52" },
  { code: "MY", label: "Malaysia", phone: "+60" },
  { code: "MZ", label: "Mozambique", phone: "+258" },
  { code: "NA", label: "Namibia", phone: "+264" },
  { code: "NC", label: "New Caledonia", phone: "+687" },
  { code: "NE", label: "Niger", phone: "+227" },
  { code: "NF", label: "Norfolk Island", phone: "+672" },
  { code: "NG", label: "Nigeria", phone: "+234" },
  { code: "NI", label: "Nicaragua", phone: "+505" },
  { code: "NL", label: "Netherlands", phone: "+31" },
  { code: "NO", label: "Norway", phone: "+47" },
  { code: "NP", label: "Nepal", phone: "+977" },
  { code: "NR", label: "Nauru", phone: "+674" },
  { code: "NU", label: "Niue", phone: "+683" },
  { code: "NZ", label: "New Zealand", phone: "+64" },
  { code: "OM", label: "Oman", phone: "+968" },
  { code: "PA", label: "Panama", phone: "+507" },
  { code: "PE", label: "Peru", phone: "+51" },
  { code: "PF", label: "French Polynesia", phone: "+689" },
  { code: "PG", label: "Papua New Guinea", phone: "+675" },
  { code: "PH", label: "Philippines", phone: "+63" },
  { code: "PK", label: "Pakistan", phone: "+92" },
  { code: "PL", label: "Poland", phone: "+48" },
  {
    code: "PM",
    label: "Saint Pierre and Miquelon",
    phone: "+508",
  },
  { code: "PN", label: "Pitcairn", phone: "+870" },
  { code: "PR", label: "Puerto Rico", phone: "+1" },
  {
    code: "PS",
    label: "Palestine, State of",
    phone: "+970",
  },
  { code: "PT", label: "Portugal", phone: "+351" },
  { code: "PW", label: "Palau", phone: "+680" },
  { code: "PY", label: "Paraguay", phone: "+595" },
  { code: "QA", label: "Qatar", phone: "+974" },
  { code: "RE", label: "Reunion", phone: "+262" },
  { code: "RO", label: "Romania", phone: "+40" },
  { code: "RS", label: "Serbia", phone: "+381" },
  { code: "RU", label: "Russian Federation", phone: "+7" },
  { code: "RW", label: "Rwanda", phone: "+250" },
  { code: "SA", label: "Saudi Arabia", phone: "+966" },
  { code: "SB", label: "Solomon Islands", phone: "+677" },
  { code: "SC", label: "Seychelles", phone: "+248" },
  { code: "SD", label: "Sudan", phone: "+249" },
  { code: "SE", label: "Sweden", phone: "+46" },
  { code: "SG", label: "Singapore", phone: "+65" },
  { code: "SH", label: "Saint Helena", phone: "+290" },
  { code: "SI", label: "Slovenia", phone: "+386" },
  {
    code: "SJ",
    label: "Svalbard and Jan Mayen",
    phone: "+47",
  },
  { code: "SK", label: "Slovakia", phone: "+421" },
  { code: "SL", label: "Sierra Leone", phone: "+232" },
  { code: "SM", label: "San Marino", phone: "+378" },
  { code: "SN", label: "Senegal", phone: "+221" },
  { code: "SO", label: "Somalia", phone: "+252" },
  { code: "SR", label: "Suriname", phone: "+597" },
  { code: "SS", label: "South Sudan", phone: "+211" },
  {
    code: "ST",
    label: "Sao Tome and Principe",
    phone: "+239",
  },
  { code: "SV", label: "El Salvador", phone: "+503" },
  {
    code: "SX",
    label: "Sint Maarten (Dutch part)",
    phone: "+1-721",
  },
  {
    code: "SY",
    label: "Syrian Arab Republic",
    phone: "+963",
  },
  { code: "SZ", label: "Swaziland", phone: "+268" },
  {
    code: "TC",
    label: "Turks and Caicos Islands",
    phone: "+1-649",
  },
  { code: "TD", label: "Chad", phone: "+235" },
  {
    code: "TF",
    label: "French Southern Territories",
    phone: "+262",
  },
  { code: "TG", label: "Togo", phone: "+228" },
  { code: "TH", label: "Thailand", phone: "+66" },
  { code: "TJ", label: "Tajikistan", phone: "+992" },
  { code: "TK", label: "Tokelau", phone: "+690" },
  { code: "TL", label: "Timor-Leste", phone: "+670" },
  { code: "TM", label: "Turkmenistan", phone: "+993" },
  { code: "TN", label: "Tunisia", phone: "+216" },
  { code: "TO", label: "Tonga", phone: "+676" },
  { code: "TR", label: "Turkey", phone: "+90" },
  {
    code: "TT",
    label: "Trinidad and Tobago",
    phone: "+1-868",
  },
  { code: "TV", label: "Tuvalu", phone: "+688" },
  {
    code: "TW",
    label: "Taiwan",
    phone: "+886",
  },
  {
    code: "TZ",
    label: "United Republic of Tanzania",
    phone: "+255",
  },
  { code: "UA", label: "Ukraine", phone: "+380" },
  { code: "UG", label: "Uganda", phone: "+256" },
  {
    code: "US",
    label: "United States",
    phone: "+1",
    suggested: true,
  },
  { code: "UY", label: "Uruguay", phone: "+598" },
  { code: "UZ", label: "Uzbekistan", phone: "+998" },
  {
    code: "VA",
    label: "Holy See (Vatican City State)",
    phone: "+379",
  },
  {
    code: "VC",
    label: "Saint Vincent and the Grenadines",
    phone: "+1-784",
  },
  { code: "VE", label: "Venezuela", phone: "+58" },
  {
    code: "VG",
    label: "British Virgin Islands",
    phone: "+1-284",
  },
  {
    code: "VI",
    label: "US Virgin Islands",
    phone: "+1-340",
  },
  { code: "VN", label: "Vietnam", phone: "+84" },
  { code: "VU", label: "Vanuatu", phone: "+678" },
  { code: "WF", label: "Wallis and Futuna", phone: "+681" },
  { code: "WS", label: "Samoa", phone: "+685" },
  { code: "XK", label: "Kosovo", phone: "+383" },
  { code: "YE", label: "Yemen", phone: "+967" },
  { code: "YT", label: "Mayotte", phone: "+262" },
  { code: "ZA", label: "South Africa", phone: "+27" },
  { code: "ZM", label: "Zambia", phone: "+260" },
  { code: "ZW", label: "Zimbabwe", phone: "+263" },
]

export const testimonies = [
  {
    id: 1,
    author: "Kateryna",
    location: "Canada",
    img: "/images/parent-Kateryna.webp",
    summary: `My 11-year-old is absolutely engaged and progressing remarkably with his coding skills.`,
    shortText: `"I am thrilled to share my experience with my son's experience at Xelaris! 
As a parent, I find the organization to 
be impeccable, making everything..."`,
    text: `"I am thrilled to share my experience with my son's experience at Xelaris! As a parent, I find the organization to be impeccable, making everything easy and straightforward.
    My 11-year-old is absolutely engaged and progressing remarkably with his coding skills. What I appreciate most is how the projects are designed to be relatable to real-life situations. For instance, simulating a banking machine not only teaches coding but also introduces important finance concepts in a fun and interactive way.

  This creative approach to learning really sets this program apart. I can't say enough about Sam, my son educator. The bond he has formed with the students is incredible—he is engaging, supportive, and knows just how to challenge them without overwhelming them.

  It's a perfect balance that keeps my son excited about learning. Additionally, the convenience of virtual classes is 
  a huge plus! Being able to sign in from anywhere makes it so easy for us to fit learning into our busy schedule. Overall, I highly recommend this coding education company to any parent looking to enhance their child's skills in a fun and meaningful way!."`,
  },
  {
    id: 2,
    author: "Alice Richardson",
    img: "/images/parent-Alice_Richardson.webp",
    location: "Indonesia",
    summary: `They provides excellent coding classes and has great teachers who motivates students to grow.`,
    shortText: `"My son loves his coding classes at Xelaris. Sam is an excellent coding teacher that always pushes him to learn more and reach his full potential!..."`,
    text: `"My son loves his coding classes at Xelaris. Sam is an excellent coding teacher that always pushes him to learn more and reach his full potential!..."`,
  },
  {
    id: 3,
    author: "Hameed",
    img: "/images/parent-Hameed.webp",
    location: "United States",
    summary: `They teach real-world technologies that are widely used in the work place.`,
    shortText: `"As a software engineer, I can confidently say that Xelaris is an exceptional company for teaching children programming in a fun and..."`,
    text: `"As a software engineer, I can confidently say that Xelaris is an exceptional company for teaching children programming in a fun and..."`,
  },
  {
    id: 4,
    author: "Roxane Cosnard des Closets",
    img: "/images/parent-Roxane_Cosnard_des_Closets.webp",
    location: "Singapore",
    summary: `The program isn't just about coding, it's about teaching kids to solve problems.`,
    shortText: `"We were in disbelief. We were not
prepared for the speed of execution."`,
    text: `"We were in disbelief. We were not
prepared for the speed of execution."`,
  },
  {
    id: 5,
    author: "Tijana Ivanovic",
    img: "",
    location: "United States",
    summary: `"I have never seen her so motivated or having fun with homework!"`,
    shortText: ``,
    text: `My 10-year-old daughter has been loving her coding lessons with Xelaris. She is taking two, 45-minute lessons per week, and is doing homework for each. I have never seen her so motivated or having fun with homework - even asking for more! The topics and exercises are age-appropriate but also tuned in to individual progress and ability. I definitely feel like she is getting a head start with valuable life skills while having fun. And i love to see her code way more than watch mindless videos online!`,
  },
  {
    id: 6,
    author: "Gottlie Caroline",
    img: "",
    location: "Monaco",
    summary: `"She really enjoyed it and would strongly recommend Xelaris in teaching coding."`,
    shortText: ``,
    text: `The one-on-one classes at Xelaris have been a game-changer! My daughter has always found e-learning a bit impersonal but the personalized approach here has made all the difference. She absolutely loves her sessions and her teacher Sophia is a perfect fit. She's supportive, engaging and inspiring. I've already recommended Xelaris to two friends and I'll keep spreading the word!`,
  },
  {
    id: 7,
    author: "Vivian Lam",
    img: "",
    location: "United States",
    summary: `"Communication and updates have been amazing after each session."`,
    shortText: ``,
    text: `My 11 year old son, Owen has been learning with Sam for 6 months now and Owen has learned so much about coding. Sam is very patient and always willing to help whenever Owen has questions. Communication and updates have been amazing after each session. Owen looks forward to learn more about coding with Sam. Thank you!`,
  },
  {
    id: 8,
    author: "Arkady A.",
    img: "",
    location: "Canada",
    summary: `"He really enjoyed it and would strongly recommend Xelaris in teaching coding."`,
    shortText: ``,
    text: `My son took coding classes from Xelaris.  He learned HTML and Python. Classes were fun, informative and engaging. He really enjoyed it and would strongly recommend Xelaris services in teaching coding.`,
  },
]
export const questions = [
  {
    id: 1,
    question: "Why should kids and teens learn to code?",
    answer: `Coding offers a multitude of benefits for kids. It fosters logical thinking, problem-solving skills, and creativity, as kids learn to break down complex problems into smaller, manageable steps. These skills are invaluable not only in coding but also in various aspects of life.`,
  },
  {
    id: 2,
    question: "What ages are the classes for?",
    answer: `Our classes cater to students aged 7-18. If your child is outside this age range or you're seeking options for adults, reach out to us, and we'll help find the right program for you.`,
  },
  {
    id: 3,
    question: "How can I track my child's progress?",
    answer: `A key aspect of our coding courses for kids and teens is keeping parents informed on what happens during the online coding class. Instructors send session notes after each class detailing what they worked on and homework.`,
  },
  {
    id: 4,
    question: "What courses does Xelaris offer?",
    answer: `Xelaris currently offers live online coding classes for kids and teens. Our coding courses include Scratch Programming, Python, App Development, Web Development, Game Development, Data Science for kids, and UX/UI Design`,
  },
  {
    id: 5,
    question: "Is the coding course schedule flexible?",
    answer: `Yes! You can work the classes around your child's schedule by selecting any time and any day that works for you.`,
  },
  {
    id: 6,
    question: "How can I track my child's progress?",
    answer: `A key aspect of our coding courses for kids and teens is keeping parents informed on what happens during the online coding class. Instructors send session notes after each class detailing what they worked on and homework.`,
  },
  {
    id: 7,
    question: "How are Xelaris teachers qualified?",
    answer: `Our teachers are handpicked experts with a proven track record in computer science. We prioritize candidates who not only have years of industry experience but also a genuine passion for teaching young minds. Our rigorous selection process ensures that only the top 1% of applicants make the cut, based on their technical expertise and exceptional communication skills.`,
  },
  {
    id: 8,
    question: "Is the coding course schedule flexible?",
    answer: `Yes! You can work the classes around your child's schedule by selecting any time and any day that works for you.`,
  },
]
export const timezoneNames: any = {
  ACDT: "Australian Central Daylight Time",
  ACST: "Australian Central Standard Time",
  ACT: "Acre Time",
  ADT: "Atlantic Daylight Time",
  AEDT: "Australian Eastern Daylight Time",
  AEST: "Australian Eastern Standard Time",
  AFT: "Afghanistan Time",
  AKDT: "Alaska Daylight Time",
  AKST: "Alaska Standard Time",
  ALMT: "Alma-Ata Time",
  AMST: "Amazon Summer Time",
  AMT: "Amazon Time",
  ANAST: "Anadyr Summer Time",
  ANAT: "Anadyr Time",
  AQTT: "Aqtobe Time",
  ART: "Argentina Time",
  AST: "Atlantic Standard Time",
  AWDT: "Australian Western Daylight Time",
  AWST: "Australian Western Standard Time",
  AZOST: "Azores Summer Time",
  AZOT: "Azores Standard Time",
  AZST: "Azerbaijan Summer Time",
  AZT: "Azerbaijan Time",
  BNT: "Brunei Darussalam Time",
  BIOT: "British Indian Ocean Time",
  BIT: "Baker Island Time",
  BOT: "Bolivia Time",
  BRST: "Brasília Summer Time",
  BRT: "Brasília Time",
  BST: "British Summer Time",
  BTT: "Bhutan Time",
  CAT: "Central Africa Time",
  CCT: "Cocos Islands Time",
  CDT: "Central Daylight Time",
  CEST: "Central European Summer Time",
  CET: "Central European Time",
  CHADT: "Chatham Island Daylight Time",
  CHAST: "Chatham Island Standard Time",
  CHOT: "Choibalsan Time",
  CHOST: "Choibalsan Summer Time",
  CHST: "Chamorro Standard Time",
  CHUT: "Chuuk Time",
  CIST: "Clipperton Island Standard Time",
  CIT: "Central Indonesia Time",
  CKT: "Cook Island Time",
  CLST: "Chile Summer Time",
  CLT: "Chile Standard Time",
  COST: "Colombia Summer Time",
  COT: "Colombia Time",
  CST: "Central Standard Time",
  CT: "China Time",
  CVT: "Cape Verde Time",
  CWST: "Central Western Standard Time",
  CXT: "Christmas Island Time",
  DAVT: "Davis Time",
  DDUT: "Dumont d'Urville Time",
  DFT: "AIX-specific equivalent of Central European Time",
  EASST: "Easter Island Summer Time",
  EAST: "Easter Island Standard Time",
  EAT: "East Africa Time",
  ECT: "Ecuador Time",
  EDT: "Eastern Daylight Time",
  EEST: "Eastern European Summer Time",
  EET: "Eastern European Time",
  EGST: "Eastern Greenland Summer Time",
  EGT: "Eastern Greenland Time",
  EST: "Eastern Standard Time",
  FET: "Further-Eastern European Time",
  FJT: "Fiji Time",
  FKST: "Falkland Islands Summer Time",
  FKT: "Falkland Islands Time",
  FNT: "Fernando de Noronha Time",
  GALT: "Galapagos Time",
  GAMT: "Gambier Time",
  GET: "Georgia Standard Time",
  GFT: "French Guiana Time",
  GILT: "Gilbert Island Time",
  GIT: "Gambier Island Time",
  GMT: "Greenwich Mean Time",
  GST: "South Georgia and the South Sandwich Islands Time",
  GYT: "Guyana Time",
  HADT: "Hawaii-Aleutian Daylight Time",
  HAST: "Hawaii-Aleutian Standard Time",
  HKT: "Hong Kong Time",
  HMT: "Heard and McDonald Islands Time",
  HOVT: "Hovd Time",
  ICT: "Indochina Time",
  IDLW: "International Day Line West time",
  IDT: "Israel Daylight Time",
  IOT: "Indian Chagos Time",
  IRDT: "Iran Daylight Time",
  IRKT: "Irkutsk Time",
  IRST: "Iran Standard Time",
  IST: "Irish Standard Time",
  JST: "Japan Standard Time",
  KGT: "Kyrgyzstan Time",
  KOST: "Kosrae Time",
  KRAT: "Krasnoyarsk Time",
  KST: "Korea Standard Time",
  LHST: "Lord Howe Standard Time",
  LINT: "Line Islands Time",
  MAGT: "Magadan Time",
  MART: "Marquesas Time",
  MAWT: "Mawson Time",
  MDT: "Mountain Daylight Time",
  MET: "Middle European Time",
  MEST: "Middle European Summer Time",
  MHT: "Marshall Islands Time",
  MIST: "Macquarie Island Station Time",
  MIT: "Marquesas Islands Time",
  MMT: "Myanmar Time",
  MSK: "Moscow Time",
  MST: "Mountain Standard Time",
  MUT: "Mauritius Time",
  MVT: "Maldives Time",
  MYT: "Malaysia Time",
  NCT: "New Caledonia Time",
  NDT: "Newfoundland Daylight Time",
  NFT: "Norfolk Island Time",
  NPT: "Nepal Time",
  NST: "Newfoundland Standard Time",
  NT: "Newfoundland Time",
  NUT: "Niue Time",
  NZDT: "New Zealand Daylight Time",
  NZST: "New Zealand Standard Time",
  OMST: "Omsk Time",
  ORAT: "Oral Time",
  PDT: "Pacific Daylight Time",
  PET: "Peru Time",
  PETT: "Kamchatka Time",
  PGT: "Papua New Guinea Time",
  PHOT: "Phoenix Island Time",
  PHT: "Philippine Time",
  PKT: "Pakistan Standard Time",
  PMDT: "Saint Pierre and Miquelon Daylight time",
  PMST: "Saint Pierre and Miquelon Standard Time",
  PONT: "Pohnpei Standard Time",
  PST: "Pacific Standard Time",
  PWT: "Palau Time",
  PYST: "Paraguay Summer Time",
  PYT: "Paraguay Time",
  RET: "Réunion Time",
  ROTT: "Rothera Research Station Time",
  SAKT: "Sakhalin Island Time",
  SAMT: "Samara Time",
  SAST: "South African Standard Time",
  SBT: "Solomon Islands Time",
  SCT: "Seychelles Time",
  SGT: "Singapore Time",
  SLST: "Sri Lanka Standard Time",
  SRET: "Srednekolymsk Time",
  SRT: "Suriname Time",
  SST: "Singapore Standard Time",
  SYOT: "Syowa Station Time",
  TAHT: "Tahiti Time",
  THA: "Thailand Standard Time",
  TFT: "Indian/Kerguelen Time",
  TJT: "Tajikistan Time",
  TKT: "Tokelau Time",
  TLT: "East Timor Time",
  TMT: "Turkmenistan Time",
  TRT: "Turkey Time",
  TOT: "Tonga Time",
  TVT: "Tuvalu Time",
  ULAT: "Ulaanbaatar Time",
  UTC: "Coordinated Universal Time",
  UYST: "Uruguay Summer Time",
  UYT: "Uruguay Standard Time",
  UZT: "Uzbekistan Time",
  VET: "Venezuelan Standard Time",
  VLAT: "Vladivostok Time",
  VOLT: "Volgograd Time",
  VOST: "Vostok Station Time",
  VUT: "Vanuatu Time",
  WAKT: "Wake Island Time",
  WAST: "West Africa Summer Time",
  WAT: "West Africa Time",
  WET: "Western European Time",
  WST: "Western Standard Time",
  YAKT: "Yakutsk Time",
  YEKT: "Yekaterinburg Time",
}

export const timezoneToCountry: any = {
  "Africa/Abidjan": "Côte d'Ivoire",
  "Africa/Accra": "Ghana",
  "Africa/Addis_Ababa": "Ethiopia",
  "Africa/Algiers": "Algeria",
  "Africa/Asmara": "Eritrea",
  "Africa/Bamako": "Mali",
  "Africa/Bangui": "Central African Republic",
  "Africa/Banjul": "Gambia",
  "Africa/Bissau": "Guinea-Bissau",
  "Africa/Blantyre": "Malawi",
  "Africa/Brazzaville": "Republic of the Congo",
  "Africa/Bujumbura": "Burundi",
  "Africa/Cairo": "Egypt",
  "Africa/Casablanca": "Morocco",
  "Africa/Ceuta": "Spain",
  "Africa/Conakry": "Guinea",
  "Africa/Dakar": "Senegal",
  "Africa/Dar_es_Salaam": "Tanzania",
  "Africa/Djibouti": "Djibouti",
  "Africa/Douala": "Cameroon",
  "Africa/El_Aaiun": "Western Sahara",
  "Africa/Freetown": "Sierra Leone",
  "Africa/Gaborone": "Botswana",
  "Africa/Harare": "Zimbabwe",
  "Africa/Johannesburg": "South Africa",
  "Africa/Juba": "South Sudan",
  "Africa/Kampala": "Uganda",
  "Africa/Khartoum": "Sudan",
  "Africa/Kigali": "Rwanda",
  "Africa/Kinshasa": "Democratic Republic of the Congo",
  "Africa/Lagos": "Nigeria",
  "Africa/Libreville": "Gabon",
  "Africa/Lome": "Togo",
  "Africa/Luanda": "Angola",
  "Africa/Lubumbashi": "Democratic Republic of the Congo",
  "Africa/Lusaka": "Zambia",
  "Africa/Malabo": "Equatorial Guinea",
  "Africa/Maputo": "Mozambique",
  "Africa/Maseru": "Lesotho",
  "Africa/Mbabane": "Eswatini",
  "Africa/Mogadishu": "Somalia",
  "Africa/Monrovia": "Liberia",
  "Africa/Nairobi": "Kenya",
  "Africa/Ndjamena": "Chad",
  "Africa/Niamey": "Niger",
  "Africa/Nouakchott": "Mauritania",
  "Africa/Ouagadougou": "Burkina Faso",
  "Africa/Porto-Novo": "Benin",
  "Africa/Sao_Tome": "São Tomé and Príncipe",
  "Africa/Tripoli": "Libya",
  "Africa/Tunis": "Tunisia",
  "Africa/Windhoek": "Namibia",
  "America/Adak": "United States",
  "America/Anchorage": "United States",
  "America/Anguilla": "Anguilla",
  "America/Antigua": "Antigua and Barbuda",
  "America/Araguaina": "Brazil",
  "America/Argentina/Buenos_Aires": "Argentina",
  "America/Argentina/Catamarca": "Argentina",
  "America/Argentina/Cordoba": "Argentina",
  "America/Argentina/Jujuy": "Argentina",
  "America/Argentina/La_Rioja": "Argentina",
  "America/Argentina/Mendoza": "Argentina",
  "America/Argentina/Rio_Gallegos": "Argentina",
  "America/Argentina/Salta": "Argentina",
  "America/Argentina/San_Juan": "Argentina",
  "America/Argentina/San_Luis": "Argentina",
  "America/Argentina/Tucuman": "Argentina",
  "America/Argentina/Ushuaia": "Argentina",
  "America/Aruba": "Aruba",
  "America/Asuncion": "Paraguay",
  "America/Atikokan": "Canada",
  "America/Bahia": "Brazil",
  "America/Bahia_Banderas": "Mexico",
  "America/Barbados": "Barbados",
  "America/Belem": "Brazil",
  "America/Belize": "Belize",
  "America/Blanc-Sablon": "Canada",
  "America/Boa_Vista": "Brazil",
  "America/Bogota": "Colombia",
  "America/Boise": "United States",
  "America/Cambridge_Bay": "Canada",
  "America/Campo_Grande": "Brazil",
  "America/Cancun": "Mexico",
  "America/Caracas": "Venezuela",
  "America/Cayenne": "French Guiana",
  "America/Cayman": "Cayman Islands",
  "America/Chicago": "United States",
  "America/Chihuahua": "Mexico",
  "America/Costa_Rica": "Costa Rica",
  "America/Creston": "Canada",
  "America/Cuiaba": "Brazil",
  "America/Curacao": "Curaçao",
  "America/Danmarkshavn": "Greenland",
  "America/Dawson": "Canada",
  "America/Dawson_Creek": "Canada",
  "America/Denver": "United States",
  "America/Detroit": "United States",
  "America/Dominica": "Dominica",
  "America/Edmonton": "Canada",
  "America/Eirunepe": "Brazil",
  "America/El_Salvador": "El Salvador",
  "America/Fort_Nelson": "Canada",
  "America/Fortaleza": "Brazil",
  "America/Glace_Bay": "Canada",
  "America/Godthab": "Greenland",
  "America/Goose_Bay": "Canada",
  "America/Grand_Turk": "Turks and Caicos Islands",
  "America/Grenada": "Grenada",
  "America/Guadeloupe": "Guadeloupe",
  "America/Guatemala": "Guatemala",
  "America/Guayaquil": "Ecuador",
  "America/Guyana": "Guyana",
  "America/Halifax": "Canada",
  "America/Havana": "Cuba",
  "America/Hermosillo": "Mexico",
  "America/Indiana/Indianapolis": "United States",
  "America/Indiana/Knox": "United States",
  "America/Indiana/Marengo": "United States",
  "America/Indiana/Petersburg": "United States",
  "America/Indiana/Tell_City": "United States",
  "America/Indiana/Vevay": "United States",
  "America/Indiana/Vincennes": "United States",
  "America/Indiana/Winamac": "United States",
  "America/Inuvik": "Canada",
  "America/Iqaluit": "Canada",
  "America/Jamaica": "Jamaica",
  "America/Juneau": "United States",
  "America/Kentucky/Louisville": "United States",
  "America/Kentucky/Monticello": "United States",
  "America/Kralendijk": "Bonaire",
  "America/La_Paz": "Bolivia",
  "America/Lima": "Peru",
  "America/Los_Angeles": "United States",
  "America/Lower_Princes": "Sint Maarten",
  "America/Maceio": "Brazil",
  "America/Managua": "Nicaragua",
  "America/Manaus": "Brazil",
  "America/Marigot": "Saint Martin",
  "America/Martinique": "Martinique",
  "America/Matamoros": "Mexico",
  "America/Mazatlan": "Mexico",
  "America/Menominee": "United States",
  "America/Merida": "Mexico",
  "America/Metlakatla": "United States",
  "America/Mexico_City": "Mexico",
  "America/Miquelon": "Saint Pierre and Miquelon",
  "America/Moncton": "Canada",
  "America/Monterrey": "Mexico",
  "America/Montevideo": "Uruguay",
  "America/Montserrat": "Montserrat",
  "America/Nassau": "Bahamas",
  "America/New_York": "United States",
  "America/Nipigon": "Canada",
  "America/Nome": "United States",
  "America/Noronha": "Brazil",
  "America/North_Dakota/Beulah": "United States",
  "America/North_Dakota/Center": "United States",
  "America/North_Dakota/New_Salem": "United States",
  "America/Ojinaga": "Mexico",
  "America/Panama": "Panama",
  "America/Pangnirtung": "Canada",
  "America/Paramaribo": "Suriname",
  "America/Phoenix": "United States",
  "America/Port-au-Prince": "Haiti",
  "America/Port_of_Spain": "Trinidad and Tobago",
  "America/Porto_Velho": "Brazil",
  "America/Puerto_Rico": "Puerto Rico",
  "America/Punta_Arenas": "Chile",
  "America/Rainy_River": "Canada",
  "America/Rankin_Inlet": "Canada",
  "America/Recife": "Brazil",
  "America/Regina": "Canada",
  "America/Resolute": "Canada",
  "America/Rio_Branco": "Brazil",
  "America/Santarem": "Brazil",
  "America/Santiago": "Chile",
  "America/Santo_Domingo": "Dominican Republic",
  "America/Sao_Paulo": "Brazil",
  "America/Scoresbysund": "Greenland",
  "America/Sitka": "United States",
  "America/St_Barthelemy": "Saint Barthelemy",
  "America/St_Johns": "Canada",
  "America/St_Kitts": "Saint Kitts and Nevis",
  "America/St_Lucia": "Saint Lucia",
  "America/St_Thomas": "United States Virgin Islands",
  "America/St_Vincent": "Saint Vincent and the Grenadines",
  "America/Swift_Current": "Canada",
  "America/Tegucigalpa": "Honduras",
  "America/Thule": "Greenland",
  "America/Thunder_Bay": "Canada",
  "America/Tijuana": "Mexico",
  "America/Toronto": "Canada",
  "America/Tortola": "British Virgin Islands",
  "America/Vancouver": "Canada",
  "America/Whitehorse": "Canada",
  "America/Winnipeg": "Canada",
  "America/Yakutat": "United States",
  "America/Yellowknife": "Canada",
  "Antarctica/Casey": "Antarctica",
  "Antarctica/Davis": "Antarctica",
  "Antarctica/DumontDUrville": "Antarctica",
  "Antarctica/Macquarie": "Macquarie Island",
  "Antarctica/Mawson": "Antarctica",
  "Antarctica/Palmer": "Antarctica",
  "Antarctica/Rothera": "Antarctica",
  "Antarctica/Syowa": "Antarctica",
  "Antarctica/Troll": "Antarctica",
  "Antarctica/Vostok": "Antarctica",
  "Arctic/Longyearbyen": "Svalbard and Jan Mayen",
  "Asia/Aden": "Yemen",
  "Asia/Almaty": "Kazakhstan",
  "Asia/Amman": "Jordan",
  "Asia/Anadyr": "Russia",
  "Asia/Aqtau": "Kazakhstan",
  "Asia/Aqtobe": "Kazakhstan",
  "Asia/Ashgabat": "Turkmenistan",
  "Asia/Atyrau": "Kazakhstan",
  "Asia/Baghdad": "Iraq",
  "Asia/Bahrain": "Bahrain",
  "Asia/Baku": "Azerbaijan",
  "Asia/Bangkok": "Thailand",
  "Asia/Barnaul": "Russia",
  "Asia/Beirut": "Lebanon",
  "Asia/Bishkek": "Kyrgyzstan",
  "Asia/Brunei": "Brunei",
  "Asia/Chita": "Russia",
  "Asia/Choibalsan": "Mongolia",
  "Asia/Colombo": "Sri Lanka",
  "Asia/Damascus": "Syria",
  "Asia/Dhaka": "Bangladesh",
  "Asia/Dili": "East Timor",
  "Asia/Dubai": "United Arab Emirates",
  "Asia/Dushanbe": "Tajikistan",
  "Asia/Famagusta": "Cyprus",
  "Asia/Gaza": "Palestine",
  "Asia/Hebron": "Palestine",
  "Asia/Ho_Chi_Minh": "Vietnam",
  "Asia/Hong_Kong": "Hong Kong",
  "Asia/Hovd": "Mongolia",
  "Asia/Irkutsk": "Russia",
  "Asia/Jakarta": "Indonesia",
  "Asia/Jayapura": "Indonesia",
  "Asia/Jerusalem": "Israel",
  "Asia/Kabul": "Afghanistan",
  "Asia/Kamchatka": "Russia",
  "Asia/Karachi": "Pakistan",
  "Asia/Kathmandu": "Nepal",
  "Asia/Khandyga": "Russia",
  "Asia/Kolkata": "India",
  "Asia/Krasnoyarsk": "Russia",
  "Asia/Kuala_Lumpur": "Malaysia",
  "Asia/Kuching": "Malaysia",
  "Asia/Kuwait": "Kuwait",
  "Asia/Macau": "Macau",
  "Asia/Magadan": "Russia",
  "Asia/Makassar": "Indonesia",
  "Asia/Manila": "Philippines",
  "Asia/Muscat": "Oman",
  "Asia/Nicosia": "Cyprus",
  "Asia/Novokuznetsk": "Russia",
  "Asia/Novosibirsk": "Russia",
  "Asia/Omsk": "Russia",
  "Asia/Oral": "Kazakhstan",
  "Asia/Phnom_Penh": "Cambodia",
  "Asia/Pontianak": "Indonesia",
  "Asia/Pyongyang": "North Korea",
  "Asia/Qatar": "Qatar",
  "Asia/Qostanay": "Kazakhstan",
  "Asia/Qyzylorda": "Kazakhstan",
  "Asia/Riyadh": "Saudi Arabia",
  "Asia/Sakhalin": "Russia",
  "Asia/Samarkand": "Uzbekistan",
  "Asia/Seoul": "South Korea",
  "Asia/Shanghai": "China",
  "Asia/Singapore": "Singapore",
  "Asia/Srednekolymsk": "Russia",
  "Asia/Taipei": "Taiwan",
  "Asia/Tashkent": "Uzbekistan",
  "Asia/Tbilisi": "Georgia",
  "Asia/Tehran": "Iran",
  "Asia/Thimphu": "Bhutan",
  "Asia/Tokyo": "Japan",
  "Asia/Tomsk": "Russia",
  "Asia/Ulaanbaatar": "Mongolia",
  "Asia/Urumqi": "China",
  "Asia/Ust-Nera": "Russia",
  "Asia/Vientiane": "Laos",
  "Asia/Vladivostok": "Russia",
  "Asia/Yakutsk": "Russia",
  "Asia/Yangon": "Myanmar",
  "Asia/Yekaterinburg": "Russia",
  "Asia/Yerevan": "Armenia",
  "Atlantic/Azores": "Portugal",
  "Atlantic/Bermuda": "Bermuda",
  "Atlantic/Canary": "Spain",
  "Atlantic/Cape_Verde": "Cape Verde",
  "Atlantic/Faroe": "Faroe Islands",
  "Atlantic/Madeira": "Portugal",
  "Atlantic/Reykjavik": "Iceland",
  "Atlantic/South_Georgia": "South Georgia and the South Sandwich Islands",
  "Atlantic/Stanley": "Falkland Islands",
  "Australia/Adelaide": "Australia",
  "Australia/Brisbane": "Australia",
  "Australia/Broken_Hill": "Australia",
  "Australia/Currie": "Australia",
  "Australia/Darwin": "Australia",
  "Australia/Eucla": "Australia",
  "Australia/Hobart": "Australia",
  "Australia/Lindeman": "Australia",
  "Australia/Lord_Howe": "Australia",
  "Australia/Melbourne": "Australia",
  "Australia/Perth": "Australia",
  "Australia/Sydney": "Australia",
  "Europe/Amsterdam": "Netherlands",
  "Europe/Andorra": "Andorra",
  "Europe/Astrakhan": "Russia",
  "Europe/Athens": "Greece",
  "Europe/Belgrade": "Serbia",
  "Europe/Berlin": "Germany",
  "Europe/Bratislava": "Slovakia",
  "Europe/Brussels": "Belgium",
  "Europe/Bucharest": "Romania",
  "Europe/Budapest": "Hungary",
  "Europe/Busingen": "Germany",
  "Europe/Chisinau": "Moldova",
  "Europe/Copenhagen": "Denmark",
  "Europe/Dublin": "Ireland",
  "Europe/Gibraltar": "Gibraltar",
  "Europe/Guernsey": "Guernsey",
  "Europe/Helsinki": "Finland",
  "Europe/Isle_of_Man": "Isle of Man",
  "Europe/Istanbul": "Turkey",
  "Europe/Jersey": "Jersey",
  "Europe/Kaliningrad": "Russia",
  "Europe/Kiev": "Ukraine",
  "Europe/Kirov": "Russia",
  "Europe/Lisbon": "Portugal",
  "Europe/Ljubljana": "Slovenia",
  "Europe/London": "United Kingdom",
  "Europe/Luxembourg": "Luxembourg",
  "Europe/Madrid": "Spain",
  "Europe/Malta": "Malta",
  "Europe/Mariehamn": "Åland Islands",
  "Europe/Minsk": "Belarus",
  "Europe/Monaco": "Monaco",
  "Europe/Moscow": "Russia",
  "Europe/Oslo": "Norway",
  "Europe/Paris": "France",
  "Europe/Podgorica": "Montenegro",
  "Europe/Prague": "Czech Republic",
  "Europe/Riga": "Latvia",
  "Europe/Rome": "Italy",
  "Europe/Samara": "Russia",
  "Europe/San_Marino": "San Marino",
  "Europe/Sarajevo": "Bosnia and Herzegovina",
  "Europe/Saratov": "Russia",
  "Europe/Simferopol": "Russia",
  "Europe/Skopje": "North Macedonia",
  "Europe/Sofia": "Bulgaria",
  "Europe/Stockholm": "Sweden",
  "Europe/Tallinn": "Estonia",
  "Europe/Tirane": "Albania",
  "Europe/Ulyanovsk": "Russia",
  "Europe/Uzhgorod": "Ukraine",
  "Europe/Vaduz": "Liechtenstein",
  "Europe/Vatican": "Vatican City",
  "Europe/Vienna": "Austria",
  "Europe/Vilnius": "Lithuania",
  "Europe/Volgograd": "Russia",
  "Europe/Warsaw": "Poland",
  "Europe/Zagreb": "Croatia",
  "Europe/Zaporozhye": "Ukraine",
  "Europe/Zurich": "Switzerland",
  "Indian/Antananarivo": "Madagascar",
  "Indian/Chagos": "British Indian Ocean Territory",
  "Indian/Christmas": "Christmas Island",
  "Indian/Cocos": "Cocos (Keeling) Islands",
  "Indian/Comoro": "Comoros",
  "Indian/Kerguelen": "French Southern Territories",
  "Indian/Mahe": "Seychelles",
  "Indian/Maldives": "Maldives",
  "Indian/Mauritius": "Mauritius",
  "Indian/Mayotte": "Mayotte",
  "Indian/Reunion": "Réunion",
  "Pacific/Apia": "Samoa",
  "Pacific/Auckland": "New Zealand",
  "Pacific/Bougainville": "Papua New Guinea",
  "Pacific/Chatham": "New Zealand",
  "Pacific/Chuuk": "Micronesia",
  "Pacific/Easter": "Chile",
  "Pacific/Efate": "Vanuatu",
  "Pacific/Enderbury": "Kiribati",
  "Pacific/Fakaofo": "Tokelau",
  "Pacific/Fiji": "Fiji",
  "Pacific/Funafuti": "Tuvalu",
  "Pacific/Galapagos": "Ecuador",
  "Pacific/Gambier": "French Polynesia",
  "Pacific/Guadalcanal": "Solomon Islands",
  "Pacific/Guam": "Guam",
  "Pacific/Honolulu": "United States",
  "Pacific/Kiritimati": "Kiribati",
  "Pacific/Kosrae": "Micronesia",
  "Pacific/Kwajalein": "Marshall Islands",
  "Pacific/Majuro": "Marshall Islands",
  "Pacific/Marquesas": "French Polynesia",
  "Pacific/Midway": "United States Minor Outlying Islands",
  "Pacific/Nauru": "Nauru",
  "Pacific/Niue": "Niue",
  "Pacific/Norfolk": "Norfolk Island",
  "Pacific/Noumea": "New Caledonia",
  "Pacific/Pago_Pago": "American Samoa",
  "Pacific/Palau": "Palau",
  "Pacific/Pitcairn": "Pitcairn Islands",
  "Pacific/Pohnpei": "Micronesia",
  "Pacific/Port_Moresby": "Papua New Guinea",
  "Pacific/Rarotonga": "Cook Islands",
  "Pacific/Saipan": "Northern Mariana Islands",
  "Pacific/Tahiti": "French Polynesia",
  "Pacific/Tarawa": "Kiribati",
  "Pacific/Tongatapu": "Tonga",
  "Pacific/Wake": "United States Minor Outlying Islands",
  "Pacific/Wallis": "Wallis and Futuna",
  UTC: "Coordinated Universal Time",
}
