import type { Metadata } from "next";
import { Inter, Spectral } from "next/font/google";
import "./globals.css";

const spectral = Spectral({
  subsets: ["latin"],

  weight: ["400", "500", "600", "700"],

  display: "swap",
  variable: "--font-spectral",
});
const interSans = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Xelaris",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${interSans.variable}  ${spectral.variable}  antialiased flex flex-col min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
